 NAM MITS
*TO PATCH 680 BASIC TO 77-68
*WITH ACIA AT PORT 1
*JAN 11 1978  MICHAEL HOLLEY
*REV 4   SEPT 4, 1978
*MODIFIED TO WORK WITH 77-68 SEPT 30, 2016 SWYNN
*THIS IS A CLONE OF THE ROM MONITOR CODE WITH ECHO REMOVED

 ORG $0150
$00

 ORG $A092
ACIACS EQU $8000
ACIADA EQU $8001

*POLE FOR CHARACTER
*SETS CARRY IF CHARACTER IS IN BUFFER
*CLOBBERS B REG
POLCAT LDA B ACIACS ACIA STATUS TO B
 ASR B ROTATE RDRF BIT INTO CARRY
 RTS RETURN

*INPUT ONE CHARACTER ACC B
INCH BSR POLCAT ACIA STATUC TO A REG
 BCC INCH RECEIVE NOT READY
 LDA B #$7F MASK FOR PARITY REMOVAL
 AND B ACIADA GET CARACTER
 RTS 

*OUTCH OUTPUTS CHARACTER IN B
OUTCH PSH B SAVE CHAR
OUTC1 BSR POLCAT ACIA STATUS TO B REG
 ASR B
 BCC OUTC1 XMIT NOT READY
 PUL B CHAR BACK TO B REG
 AND B #$7F
 STA B ACIADA OUTPUT CHARACTER
 RTS

*PATCHES TO MITS BASIC
 ORG $041F
 JSR INCH

 ORG $0618
 JSR POLCAT

 ORG $08AD
 JSR OUTCH

 END
